export const AUDIT_ACTIONS = [
  'USER_REGISTERED',
  'LOGIN_SUCCEEDED',
  'LOGIN_FAILED',
  'PASSWORD_CHANGED',
  'SESSION_REUSE_DETECTED',
  'ITEM_REPORTED',
  'ITEM_REMOVED',
  'CLAIM_SUBMITTED',
  'CLAIM_APPROVED',
  'CLAIM_REJECTED',
  'CLAIM_CANCELLED',
  'HANDOVER_CONFIRMED',
  'HANDOVER_CONFIRMED_BY_STAFF',
  'HANDOVER_LOCKED',
  'CLAIM_EXPIRED',
  'USER_ROLE_CHANGED',
  'USER_SUSPENDED',
  'USER_REACTIVATED',
  'ITEM_FLAGGED',
  'REPORT_RESOLVED',
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_TARGET_TYPES = ['USER', 'ITEM', 'CLAIM', 'SESSION', 'REPORT'] as const;
export type AuditTargetType = (typeof AUDIT_TARGET_TYPES)[number];
